# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cctv_pb2 as cctv__pb2


class CCTVServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamVideo = channel.stream_stream(
                '/CCTVService/StreamVideo',
                request_serializer=cctv__pb2.FrameMessage.SerializeToString,
                response_deserializer=cctv__pb2.Acknowledgement.FromString,
                )


class CCTVServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamVideo(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CCTVServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamVideo': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamVideo,
                    request_deserializer=cctv__pb2.FrameMessage.FromString,
                    response_serializer=cctv__pb2.Acknowledgement.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CCTVService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CCTVService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamVideo(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/CCTVService/StreamVideo',
            cctv__pb2.FrameMessage.SerializeToString,
            cctv__pb2.Acknowledgement.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
